# Updated to use root context so Docker can access yarn.lock and .yarn for workspace build
version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: apps/frontend/shell/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ..
      dockerfile: apps/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vista
      - SPRING_DATASOURCE_USERNAME=vista
      - SPRING_DATASOURCE_PASSWORD=vista
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vista
      - POSTGRES_USER=vista
      - POSTGRES_PASSWORD=vista
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vista"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
