apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-restricted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:restricted-v2
subjects:
- kind: ServiceAccount
  name: postgres-sa
  namespace: brandonarka3-dev 